### ISSUE TITLE
Page numbers are being displayed vertically

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#38]
The page numbers at the bottom of the page is being displayed vertically:

![image](https://user-images.githubusercontent.com/61739458/78143605-66c53180-7426-11ea-80d6-671aafbccba7.png)

Can we please amend so the page numbers are displayed horizontally, thanks

**Comment by hnryjmes** [comment]
The pagination CSS was not merged successfully for the last develop branch that the most recent deployment was based on - I have checked master and the pagination CSS appears properly, so for the next deployment this should disappear.

**Comment by rahulbist** [comment]
Page numbers are now fixed and being displayed horizontally:

![image](https://user-images.githubusercontent.com/61739458/78542987-df920800-77ef-11ea-86b5-0cab5702fa82.png)
