### ISSUE TITLE
Amend enquiries to be displayed in the order: most recently received 

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#39]
In the Enquiries screen (homepage), the enquiries being displayed is sorted by oldest - newest.

Can we amended the sorting to display the enquiries from newest - oldest

**Comment by saruniitr** [comment]
pushed a fix to `master`, it can be closed after verifying in the deployed app

**Comment by rahulbist** [comment]
Closing as enquiries are now being sorted by newest - oldest
