### ISSUE TITLE
Date last updated field not updating within the Enquiries screen

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#40]
When an enquiry is updated, the "Date last updated" field is updated to correlate the current date-stamp however, when you review an enquiry from the homepage (Enquiries screen), the field value remains blank:

![image](https://user-images.githubusercontent.com/61739458/78145561-f370ef00-7428-11ea-8e26-15479dfd3ce6.png)

**Comment by hnryjmes** [comment]
The hotfix for this is already on master, please close when we verify this is fixed

**Comment by saruniitr** [comment]
The error was because of using incorrect variable in the template.
`updated` was used instead of `modified`

**Comment by rahulbist** [comment]
Closing as issue has now passed testing:

![image](https://user-images.githubusercontent.com/61739458/78367342-d4559700-75b9-11ea-9eb1-703d0f12d74a.png)
