### ISSUE TITLE
Company assigned link should point to company record in Data Hub

### ISSUE THREAD

**Issue by hnryjmes** [uktrade/enquiry-mgmt-tool#41]
After using company search, and a DH company is assigned to an enquiry, the link visible in Detail/Edit view should point to the company record in Data Hub. 

At the moment the link goes to # i.e. it is still a dummy link.

**Comment by hnryjmes** [comment]
see also:https://github.com/uktrade/enquiry-mgmt-tool/issues/61

**Comment by rahulbist** [comment]
This is now resolved.

When the link was clicked, I was directed to the Data Hub UI and to the particular Company record
