### ISSUE TITLE
Missing value "Engaged in dialogue" on Enquiry stage reference data

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#54]
The reference data for “Enquiry stage” is missing the value “Engaged in dialogue”. Please ensure this is included:

![image](https://user-images.githubusercontent.com/61739458/78154933-c0345d00-7434-11ea-862c-e36662635bc7.png)

**Comment by hnryjmes** [comment]
The hotfix for this is now on master

**Comment by rahulbist** [comment]
![image](https://user-images.githubusercontent.com/61739458/78376831-c5291600-75c6-11ea-974c-8215dd1a51b2.png)
