### ISSUE TITLE
HPO details (Second HPO selection and Third HPO selection) not appearing

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#55]
If an enquiry has been modified and “Second HPO selection” and “Third HPO selection” has been populated, these values should appear on the read-only screen when providing the full summary of enquiry data (Submit to Data Hub screen).

Screenshot of values chosen:

![image](https://user-images.githubusercontent.com/61739458/78155025-dc37fe80-7434-11ea-97af-22e881343981.png)

Expected value: 

HPO details:

“First HPO selection” should appear with “Food production”

“Second HPO selection” should appear with “UK rail”

 “Third HPO selection” should appear with “Lightweight structures”

Actual outcome (only “First HPO selection” is appearing):

![image](https://user-images.githubusercontent.com/61739458/78155078-ebb74780-7434-11ea-886f-7013041cb8a3.png)

**Comment by hnryjmes** [comment]
Hotfix for this now on master

**Comment by rahulbist** [comment]
"First HPO", "Second HPO selection" and "Third HPO selection" fields are now appearing:

![image](https://user-images.githubusercontent.com/61739458/78543494-a1e1af00-77f0-11ea-9811-e4ff6a28ac0f.png)
