### ISSUE TITLE
Company in Data Hub hyperlink

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#61]
When you have assigned an Enquiry to a Data Hub company record, the field "Company in Data Hub" will contain the Data Hub company name value. 

Additionally, this will be a hyperlink and when clicked, should direct the user to Data Hub and specifically to that Data Hub company record.

Currently, if clicked, you are directed to the same page on the Enquiry Management Tool

**Comment by hnryjmes** [comment]
see also: https://github.com/uktrade/enquiry-mgmt-tool/issues/41

**Comment by rahulbist** [comment]
Closing as this is a duplicate of #41
