### ISSUE TITLE
Where country is set to default, do not display the tag on the homepage

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#64]
When an enquiry's country has been set to default ("----"), can we not display the tag and only display the country tag when the value is not set to default:

![image](https://user-images.githubusercontent.com/61739458/78543699-f38a3980-77f0-11ea-9e9c-3ab09eb0b60b.png)

**Comment by hnryjmes** [comment]
hotfix for this is on master as of yesterday

**Comment by rahulbist** [comment]
Fixed, the country tag not longer displays when the value is set to default/"----":

![image](https://user-images.githubusercontent.com/61739458/78543868-32b88a80-77f1-11ea-95fe-5919862e0f34.png)
