### ISSUE TITLE
Can all unknown values or fields that have not been manipulated be set to "----"

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#65]
To keep consistency, can we ensure all values that are unknown or fields that have not yet been manipulated, be set to "----".

Currently, when values have not been selected, the Enquiry Management Tool displays "None" and when an invalid value has been selected/a value has been routed from great.gov.uk that does not exist on the tool displays "----"

![image](https://user-images.githubusercontent.com/61739458/78271533-2a680300-7504-11ea-9d88-2bd466bb4670.png)

Therefore, to ensure the tool is consistent on the eye, can we please ensure these fields are set to "----"

**Comment by hnryjmes** [comment]
hotfix for this now on master

**Comment by rahulbist** [comment]
Fixed, all values that are unknown or blank are displayed as "----"

![image](https://user-images.githubusercontent.com/61739458/78544029-714e4500-77f1-11ea-9faf-2b4e5b67800a.png)
