### ISSUE TITLE
Hide "Call requested" field when value is blank

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#73]
On the homepage, when an enquiry has no value for "Call requested", can this field be hidden:

![image](https://user-images.githubusercontent.com/61739458/78367728-78d7d900-75ba-11ea-8f4f-8a5c56adecab.png)

**Comment by hnryjmes** [comment]
@rahulbist actually this was a bug! the variable name was wrong, so this is now fixed. also have made it conditional, so if it is ever '----', then we don't show it in the template

hotfix for this now on master

**Comment by rahulbist** [comment]
Fixed, Call requested field is no longer displayed when value is blank: 

![image](https://user-images.githubusercontent.com/61739458/78544193-ac507880-77f1-11ea-9934-28bebaca993c.png)
